### ISSUE TITLE
Extension Error when adding the Repo to makecode.microbit.org Editor

### ISSUE THREAD

**Issue by Sharkking** [waveshare/TouchPiano#2]
Adding the Repository works, but when trying to download the hex code  to the micro:bit 
ill get an Extension Error warning and the Piano has no function

![image](https://user-images.githubusercontent.com/3736131/49941132-e6ea1f80-fee1-11e8-8cef-4c281f23f6e1.png)

PLease advice

**Comment by retrospct** [comment]
Give this a try @Sharkking 
https://github.com/waveshare/TouchPiano/pull/1#issuecomment-449540284
